version: "3.8"

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: dockerfile.dev
    container_name: eth-frontend
    ports:
      - "5173:5173" # Or change to 3000 if using Next.js
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://backend:3000
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend
  backend:
    build: 
      context: backend/
      dockerfile: dockerfile.dev
    container_name: eth-api-app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - ALCHEMY_URL=https://eth-sepolia.g.alchemy.com/v2/yU5mxV9DJB41c5YLwvjM_
      - REDIS_URL=redis://redis:6379
      - MONGO_URI=mongodb://mongo:27017/ethapi
    depends_on:
      - mongo
      - redis
    volumes:
      - ./backend:/app 
    command: ["ts-node-dev", "--respawn", "--transpile-only", "src/app.ts"]

  mongo:
    image: mongo:4.4
    container_name: eth-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: eth-redis
    ports:
      - "6379:6379"
  smart-contract:
    build: ./smart-contract
    container_name: eth-contract
    volumes:
      - ./smart-contract:/app
    working_dir: /app
    command: npx hardhat node
    ports:
      - "8545:8545"
volumes:
  mongo_data: